# Generated by Django 5.0.6 on 2024-06-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_comidas_delete_comida_rename_nombre_postres_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='apellido',
        ),
        migrations.AddField(
            model_name='registro',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
        migrations.AlterField(
            model_name='comidas',
            name='receta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postres',
            name='receta',
            field=models.TextField(),
        ),
    ]
