# Generated by Django 5.0.6 on 2024-06-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_comidas_autor_alter_postres_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidas',
            name='ingredientes',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='postres',
            name='ingredientes',
            field=models.TextField(default=None),
        ),
    ]
