# Generated by Django 5.0.6 on 2024-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_comidas_ingredientes_postres_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='profile_image',
            field=models.CharField(choices=[('burritokawaii.jpg', 'Imagen 1'), ('default.png', 'Imagen 2'), ('limon-kawaii.jpg', 'Imagen 3'), ('pizzakawaii.jpg', 'Imagen 4'), ('sushikawaii.jpg', 'Imagen 5'), ('tarta-kawaii.jpg', 'Imagen 6'), ('limon-kawaii.jpg', 'Imagen 7')], default='default.png', max_length=255),
        ),
    ]
