# Generated by Django 5.0.6 on 2024-06-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_registro_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='profile_image',
        ),
    ]
