# Generated by Django 5.0.6 on 2024-06-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_alter_comidas_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AlterField(
            model_name='comidas',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postres',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
